# Check available URLs, then upload artifact to github
name: UpdateURLList

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: test output
        run: echo Hello, world!

      - name: update apt sources
        run: sudo apt update
      
      - name: install dnsutils
        run: sudo apt install dnsutils -y

      - name: Check which URLs are available
        run: ./checker.sh # Depends on dnsutils

      - name: Upload URLs
        uses: actions/upload-artifact@v4
        with:
          name: urls_to_show
          path: urls_to_show
